#tomcat配置
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  servlet:
    context-path: /emos

spring:
  mvc:
    pathmatch:
      #兼容swagger3路径匹配模式
      matching-strategy: ant_path_matcher
  #MySQL配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://101.43.246.132:3306/emos?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
      username: root
      password: 0825
      initial-size: 8
      max-active: 16
      min-idle: 8
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  #redis配置
  redis:
    database: 0
    host: 101.43.246.132
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8
  #mongodb配置
  data:
    mongodb:
      host: 101.43.246.132
      port: 27017
      database: emos
      authentication-database: admin
      username: admin
      password: gz0825
#mybatis配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.gz.emos.wx.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    map-underscore-to-camel-case: true #支持驼峰命名
#日志输出配置
logging:
  level:
    root: info
    com.gz.emos.wx.mapper: warn
  pattern:
    console: "%d{HH:mm:ss} %-5level %msg%n"

#定义密钥和过期时间
emos:
  jwt:
    secret: abc123456 #密钥
    expire: 5         #令牌过期时间（天）
    cache-expire: 10  #令牌缓存时间（天）

#定义微信小程序id和密钥
wx:
  app-id: wx5a4fea469a375629
  app-secret: 5916081991beb6335aa7b18e3f48606b

